Repository Nonagajyeo/BanThing-dev, pull requests merged in 2025-09, with the labels that each got.

#2 feat: 사용자, 미팅, 마트, 피드백 등 관련 엔터티 추가 #1
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/refactoring.md
  .github/PULL_REQUEST_TEMPLATE.md
  backend/src/main/java/com/nathing/banthing/entity/ChatbotConversation.java
  backend/src/main/java/com/nathing/banthing/entity/ChatbotMeetingSuggestion.java
  backend/src/main/java/com/nathing/banthing/entity/Feedback.java
  backend/src/main/java/com/nathing/banthing/entity/Mart.java
  backend/src/main/java/com/nathing/banthing/entity/Meeting.java
  backend/src/main/java/com/nathing/banthing/entity/MeetingParticipant.java
  backend/src/main/java/com/nathing/banthing/entity/User.java
Labels: feat

#24 [Feat]: [BE] 카카오 소셜 로그인 + JWT 인증/토큰 관리/로그아웃 기능 구현 (#19, #20, #21, #23)
  backend/build.gradle
  backend/src/main/java/com/nathing/banthing/config/JwtAuthenticationFilter.java
  backend/src/main/java/com/nathing/banthing/config/OAuth2FailureHandler.java
  backend/src/main/java/com/nathing/banthing/config/OAuth2SuccessHandler.java
  backend/src/main/java/com/nathing/banthing/config/SecurityConfig.java
  backend/src/main/java/com/nathing/banthing/controller/.gitkeep
  backend/src/main/java/com/nathing/banthing/controller/AuthController.java
  backend/src/main/java/com/nathing/banthing/dto/request/.gitkeep
  backend/src/main/java/com/nathing/banthing/entity/User.java
  backend/src/main/java/com/nathing/banthing/repository/FeedbacksRepository.java
  backend/src/main/java/com/nathing/banthing/repository/UsersRepository.java
  backend/src/main/java/com/nathing/banthing/service/.gitkeep
  backend/src/main/java/com/nathing/banthing/service/CustomOAuth2UserService.java
  backend/src/main/java/com/nathing/banthing/util/AppProperties.java
  backend/src/main/java/com/nathing/banthing/util/CookieProperties.java
  backend/src/main/java/com/nathing/banthing/util/CookieUtil.java
  backend/src/main/java/com/nathing/banthing/util/JwtTokenProvider.java
  backend/src/main/resources/application.yml
Labels: feat

#29 [Feature] [BE] 피드백 기능 및 사용자 신뢰 점수 시스템 구현 (#15)
  backend/build.gradle
  backend/src/main/java/com/nathing/banthing/controller/FeedbackConrtoller.java
  backend/src/main/java/com/nathing/banthing/dto/enums/FeedbackSearchType.java
  backend/src/main/java/com/nathing/banthing/dto/request/FeedbackCreateRequest.java
  backend/src/main/java/com/nathing/banthing/dto/response/CommonResponse.java
  backend/src/main/java/com/nathing/banthing/dto/response/FeedbackResponse.java
  backend/src/main/java/com/nathing/banthing/dto/response/FeedbackScoreResponse.java
  backend/src/main/java/com/nathing/banthing/dto/response/UserResponse.java
  backend/src/main/java/com/nathing/banthing/entity/Feedback.java
  backend/src/main/java/com/nathing/banthing/entity/FeedbackType.java
  backend/src/main/java/com/nathing/banthing/entity/ScoreEvent.java
  backend/src/main/java/com/nathing/banthing/entity/TrustGrade.java
  backend/src/main/java/com/nathing/banthing/entity/User.java
  backend/src/main/java/com/nathing/banthing/repository/FeedbacksRepository.java
  backend/src/main/java/com/nathing/banthing/repository/MeetingParticipantsRepository.java
  backend/src/main/java/com/nathing/banthing/service/FeedbackScoreService.java
  backend/src/main/java/com/nathing/banthing/service/FeedbackService.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/data.sql
Labels: feat

#49 [Feat]: [BE] 호스트 전용 참가자 목록 조회 API 개선 (#49)
  backend/src/main/java/com/nathing/banthing/controller/MeetingController.java
  backend/src/main/java/com/nathing/banthing/dto/response/ParticipantListResponse.java
  backend/src/main/java/com/nathing/banthing/service/JoinMeetingService.java
Labels: enhancement

#50 [Feat]: [FE] 카카오 SSO 최소기능 구현 (#48)
  frontend/src/components/Layout/AppHeader.jsx
  frontend/src/components/Others/Logo.jsx
  frontend/src/pages/LoginPage.jsx
Labels: feat

#53 refactor: [BE] 사용자 ID 처리 방식 providerId 기반으로 리팩토링 (#52)
  backend/src/main/java/com/nathing/banthing/controller/MeetingController.java
  backend/src/main/java/com/nathing/banthing/service/CreateMeetingService.java
  backend/src/main/java/com/nathing/banthing/service/DeleteMeetingService.java
  backend/src/main/java/com/nathing/banthing/service/JoinMeetingService.java
  backend/src/main/java/com/nathing/banthing/service/ManageMeetingService.java
  backend/src/main/java/com/nathing/banthing/service/UpdateMeetingService.java
Labels: bug, refactor

#59 [Feat]: [FE] AppHeader, LoginPage, PopupClosePage 스타일링 및 UI 개선 (#57)
  frontend/src/components/Layout/AppHeader.jsx
  frontend/src/components/Layout/AppHeader.module.scss
  frontend/src/pages/LoginPage.jsx
  frontend/src/pages/LoginPage.module.scss
  frontend/src/pages/PopupClosePage.jsx
  frontend/src/pages/PopupClosePage.module.scss
Labels: feat

#63 [feat]: [FE] 모임 상세 페이지 기능 구현 #62
  frontend/src/App.jsx
  frontend/src/components/Meeting/MeetingCard.jsx
  frontend/src/pages/MeetingDetailPage.jsx
  frontend/src/pages/MeetingDetailPage.module.scss
  frontend/src/services/.gitkeep
  frontend/src/services/meetingDetailApi.js
Labels: feat

#67 [Feat]: [FE/BE] 모임 생성 페이지 및 라우트 가드 구현 (#61)
  backend/src/main/java/com/nathing/banthing/config/SecurityConfig.java
  backend/src/main/java/com/nathing/banthing/config/WebConfig.java
  backend/src/main/java/com/nathing/banthing/controller/MeetingController.java
  backend/src/main/java/com/nathing/banthing/service/CreateMeetingService.java
  backend/src/main/resources/application.yml
  frontend/src/components/Auth/PrivateRoute.jsx
  frontend/src/components/Meeting/MeetingCard.jsx
  frontend/src/pages/MeetingCreatePage.jsx
  frontend/src/pages/MeetingCreatePage.module.scss
  frontend/src/pages/MeetingListPage.jsx
  frontend/src/pages/MeetingListPage.module.scss
  frontend/src/routes/router-config.jsx
  frontend/src/services/MartApi.js
  frontend/src/services/createMeetingApi.js
Labels: feat

#68 [Feat]: [BE] 모임 조회 관련 기능 및 리팩토링 (#64)
  backend/src/main/java/com/nathing/banthing/controller/MeetingController.java
  backend/src/main/java/com/nathing/banthing/dto/response/MeetingProfilePageResponse.java
  backend/src/main/java/com/nathing/banthing/entity/Meeting.java
  backend/src/main/java/com/nathing/banthing/repository/MeetingsRepository.java
  backend/src/main/java/com/nathing/banthing/service/FindMeetingService.java
  backend/src/test/java/com/nathing/banthing/repository/MeetingsRepositoryTest.java
Labels: feat

#73 [Feat]: [FE] 프로필 페이지 및 헤더 UI 개선 (#60)
  frontend/src/components/Header/AppHeader.jsx
  frontend/src/components/Header/AppHeader.module.scss
  frontend/src/components/MyPage/.gitkeep
  frontend/src/components/Profile/MyInfo.jsx
  frontend/src/components/Profile/MyParticipatingGroups.jsx
  frontend/src/components/Profile/MyPendingGroups.jsx
  frontend/src/layouts/AppLayout.jsx
  frontend/src/pages/ProfilePage.jsx
  frontend/src/routes/router-config.jsx
  frontend/src/services/profileApi.js
Labels: feat

#77 [Feature] [FE/BE] 댓글 수정/삭제 기능 추가 및 UI/UX 개선
  backend/src/main/java/com/nathing/banthing/controller/CommentController.java
  backend/src/main/java/com/nathing/banthing/controller/FeedbackController.java
  backend/src/main/java/com/nathing/banthing/dto/request/CommentCreateDto.java
  backend/src/main/java/com/nathing/banthing/dto/request/CommentUpdateDto.java
  backend/src/main/java/com/nathing/banthing/dto/response/CommentListDto.java
  backend/src/main/java/com/nathing/banthing/dto/response/CommentReadDto.java
  backend/src/main/java/com/nathing/banthing/entity/Comment.java
  backend/src/main/java/com/nathing/banthing/entity/Meeting.java
  backend/src/main/java/com/nathing/banthing/entity/User.java
  backend/src/main/java/com/nathing/banthing/exception/ErrorCode.java
  backend/src/main/java/com/nathing/banthing/repository/CommentRepository.java
  backend/src/main/java/com/nathing/banthing/repository/MeetingParticipantsRepository.java
  backend/src/main/java/com/nathing/banthing/service/CommentService.java
  backend/src/main/java/com/nathing/banthing/service/CommentServiceImpl.java
  backend/src/main/java/com/nathing/banthing/service/UserService.java
  backend/src/main/resources/data.sql
  frontend/src/components/Comment/.gitkeep
  frontend/src/components/Comment/CommentForm.jsx
  frontend/src/components/Comment/CommentList.jsx
  frontend/src/components/Comment/CommentModal.jsx
  frontend/src/components/Comment/CommentModal.module.scss
  frontend/src/pages/CommentPage.jsx
  frontend/src/pages/MeetingDetailPage.jsx
  frontend/src/pages/MeetingDetailPage.module.scss
  frontend/src/routes/router-config.jsx
  frontend/src/services/meetingDetailApi.js
Labels: feat

#78 [Feat]: 모임 생성 UX 개선 및 참여자 관리 기능 구현 (#70, #69)
  backend/src/main/java/com/nathing/banthing/controller/MeetingController.java
  backend/src/main/java/com/nathing/banthing/dto/response/MeetingDetailResponse.java
  backend/src/main/java/com/nathing/banthing/dto/response/MeetingParticipantResponse.java
  backend/src/main/java/com/nathing/banthing/entity/MeetingParticipant.java
  backend/src/main/java/com/nathing/banthing/service/FindMeetingService.java
  backend/src/main/java/com/nathing/banthing/service/JoinMeetingService.java
  backend/src/main/java/com/nathing/banthing/service/ManageMeetingService.java
  frontend/src/components/Meeting/KakaoMap.jsx
  frontend/src/components/Meeting/MeetingCard.jsx
  frontend/src/components/Meeting/MeetingCardSkeleton.jsx
  frontend/src/components/Meeting/MeetingList.jsx
  frontend/src/components/Meeting/ParticipantsTab.jsx
  frontend/src/pages/MeetingCreatePage.jsx
  frontend/src/pages/MeetingCreatePage.module.scss
  frontend/src/pages/MeetingDetailPage.jsx
  frontend/src/services/createMeetingApi.js
  frontend/src/services/participantApi.js
Labels: feat

#81 [Feat]: [FE] 프로필 페이지 모임 조회, 페이징, 스타일링 및 UX 개선 (#60)
  frontend/src/components/Profile/MyInfo.jsx
  frontend/src/components/Profile/MyInfoCard.jsx
  frontend/src/components/Profile/MyInfoCard.module.scss
  frontend/src/components/Profile/MyInfoCardSkeleton.jsx
  frontend/src/components/Profile/MyInfoCardSkeleton.module.scss
  frontend/src/components/Profile/MyParticipatingGroups.jsx
  frontend/src/components/Profile/MyPendingGroups.jsx
  frontend/src/components/Profile/MyProfileMeetings.jsx
  frontend/src/components/Profile/MyProfileMeetings.module.scss
  frontend/src/loaders/.gitkeep
  frontend/src/loaders/profileMeetingLoader.js
  frontend/src/pages/LoginPage.module.scss
  frontend/src/pages/ProfilePage.jsx
  frontend/src/pages/ProfilePage.module.scss
  frontend/src/routes/router-config.jsx
Labels: feat

#88 [Feat]: [FE/BE] 사용자 약관 동의 기능 구현 (#84)
  backend/src/main/java/com/nathing/banthing/controller/UserController.java
  backend/src/main/java/com/nathing/banthing/entity/User.java
  backend/src/main/java/com/nathing/banthing/service/UserService.java
  frontend/src/components/Auth/LoadMeRoute.jsx
  frontend/src/pages/AgreementPage.jsx
  frontend/src/pages/AgreementPage.module.scss
  frontend/src/pages/LoginPage.jsx
  frontend/src/pages/ProfilePage.jsx
  frontend/src/routes/router-config.jsx
  frontend/src/services/authService.js
Labels: feat

#92 [Feat]: [BE/FE] 챗봇 로그인 처리 개선 및 키워드 기반 모임 조회 기능 추가 #91
  backend/src/main/java/com/nathing/banthing/config/ChatbotConfig.java
  backend/src/main/java/com/nathing/banthing/controller/ChatbotController.java
  backend/src/main/java/com/nathing/banthing/service/ChatbotServiceImpl.java
  frontend/src/components/Chatbot/Chatbot.jsx
  frontend/src/pages/AgreementPage.jsx
Labels: feat
